// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
import type { Metadata } from 'next'
import Script from 'next/script'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from './components/ThemeProvider'
import { BackgroundMotion } from './components/BackgroundMotion'

const themeInitScript = `(function(){try{var k='portfolio-theme';var t=localStorage.getItem(k)||'light';var r=document.documentElement;r.classList.remove('light','dark');r.classList.add(t);}catch(e){}})();`

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tihetna Mesfin - AI Engineer & Data Scientist',
  // description:
  //   'Portfolio of Tihetna Mesfin, AI Engineer & Data Scientist specializing in Computer Vision, GANs, and Agentic AI.',
  description: 'MSc in Computer Vision specializing in GANs and agentic AI systems. Building production-ready AI solutions.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} min-h-screen antialiased`}>
        <Script id="theme-init" strategy="beforeInteractive">
          {themeInitScript}
        </Script>
        <ThemeProvider>
          <BackgroundMotion />
          <div className="relative z-0">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  )
}